baseurl = "https://andlabs.github.io/"
languageCode = "en-us"
title = "andlabs UI"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "andlabs"
	description = "Simple and portable (but not inflexible) GUI library in C that uses the native GUI technologies of each platform it supports."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/andlabs/libui"

	#version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "andlabs"
	email   = "pietro10@mac.com"


[[menu.main]]
	name   = "Project libui"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "lib UI"
	url    = "libui/"
	weight = 20

[[menu.main]]
	name	= "Golang UI"
	url 	= "goui/"
	weight 	= 30

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 50



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
